"""Named protocol versions and runtime limits shared across boundaries."""

from typing import Final

SCENARIO_SCHEMA_VERSION: Final = 3
RUN_CONFIG_SCHEMA_VERSION: Final = 3
RUN_LOG_SCHEMA_VERSION: Final = 4
CAMPAIGN_CHECKPOINT_SCHEMA_VERSION: Final = 1

DEFAULT_LOOPBACK_PORT: Final = 8000
DEFAULT_ACT_LLM_TIMEOUT_SECONDS: Final = 60
DEFAULT_CAMPAIGN_LLM_TIMEOUT_SECONDS: Final = 120
MAX_PLAYTEST_ROUNDS: Final = 1000
MAX_DEVELOPER_INSTRUCTION_CHARS: Final = 8000
